baseURL = "http://amoshyc.github.io/bloguh"
languageCode = "en-us"
title = "Yu-Cheng Huang"
theme = "zmd"
publishDir = "docs"
FootnoteReturnLinkContents = "â†©"
uglyurls = true
preserveTaxonomyNames = true